#!/bin/bash

# This script should have access to your $PATH variable. 
# I have mine located in ~/bin, but you could also put it 
# in /usr/bin, or put it somewhere else and then add it to 
# your $PATH variable by editing your ~/.bashrc or something.

# To run this script, just enter your NetID in the NETID variable,
# and enter your NetID password in the PW variable. I have provided
# some more insight in the comments below, and in the comments that are
# scattered throughout uiucvpnup.

# NOTE: If something fails in the uiucvpnup for whatever reason, and 
# you see "spawn ssh ..." on the command line, and nothing happens for
# 10+ seconds, then hit CTRL-C to cancel the process, as something
# failed with the VPN connection, and SSH will hang indefinitely.
#
# Once you do get into the EWS environment, to exit the SSH, enter
# "exit" into the command process, and the SSH will exit, and the 
# vpn will be turned off, so that you resume your normal network
# connection (using uiucvpndown).
#
# Also, you can adjust the SSH address to SSH into another EWS machine
# for another course in the future. Also, the expect script, "exp", is 
# really useful for many automated tasks in the terminal, as you can 
# use it to input text when the command expects input. In this case,
# once SSH connection is established, it asks you to enter your 
# NetID password through stdin (the command line). Using exp,
# it can enter this password for you, so the entire pipeline is automated
# to get you into the EWS machine remotely. It's pretty neat.


# Enter your NetID username.
# E.g., NETID="esirois3"
NETID=""

# Enter your NetID password inside the quotation marks.
# E.g., PW="mypassword"
PW=""

# For CS426, you have a three-digit VM number that 
# has been assigned to you. Enter that here.
# E.g., VM_NUMBER="123"
VM_NUMBER=""

# This enables the VPN to UIUC's Cisco server. This allows you
# to connect to the EWS machines via SSH. I put in some notes 
# inside the uiucvpnup script to guide you in the right direction
# for changing the connection type, and the 2FA method.

# But first, we need to close any VPN tunnels if they're already 
# opened
uiucvpndown

uiucvpnup "$NETID" "$PW"


# We need to actually power on the VM first. If the VM is already
# powered on, this won't do anything, so no harm in running this
# anyways :)
start_cs426_vm "$NETID" "$PW" "$VM_NUMBER"

# This establishes the connection to the EWS machine through SSH 
# after the VPN connection is finished, although it may try to 
# SSH even if the VPN connection failed for whatever reason. 
# Like I said, just CTRL-C to exit the SSH when it hangs indefinitely, 
# and try to resolve the issue that caused the VPN connection to fail. 
# You can check the oclog.txt file for output messages from 
# the VPN script to see any connection issues.
# oclog.txt should be located in /tmp/oclog.txt
enter_cs426_env "$NETID" "$PW" "$VM_NUMBER" 

# This terminates the VPN and restores you back to your normal connection
# after you exit the SSH.
uiucvpndown
